### ISSUE TITLE
[feature request] show battery icon

### ISSUE THREAD

**Issue by tnhh00037** [AndroPlus-org/magisk-module-pixel6#1]
Hi, thank you for your hardworking.
May I ask for a version with "Navigation bar" hidden, but still show Battery icon.

I'd love to hide Navigation bar but I don't really want to care battery percentage all the time.

Thanks for your time!

**Comment by AndroPlus-org** [comment]
OK, I splitted overlay on v4.
Please use this:
https://drive.google.com/file/d/1rQkyfk3cckkONVfx5mjfV8spMRtK65kk/view?usp=sharing
