### ISSUE TITLE
機能オミットの方法について

### ISSUE THREAD

**Issue by KH0000001** [AndroPlus-org/magisk-module-pixel6#2]
開発ありがとうございます。
以下の機能をオミットしたいのですが、どこを調節すればいいでしょうか？

- バッテリーアイコンの表示
- カメラシャッター音の強制を無効化
- USB ケーブル接続時に画面がオンにならないよう変更
- 電源メニューから緊急通報や機内モードを削除

教えていただけると嬉しいです。

**Comment by AndroPlus-org** [comment]
・バッテリーアイコンの表示
/system/product/overlay/treble-overlay-google-pixel6-systemui-battery.apk を削除

・カメラシャッター音の強制を無効化
/system/product/overlay/treble-overlay-google-pixel6.apk をデコンパイルし
values/bools.xmlの
`<bool name="config_camera_sound_forced">false</bool>`
を削除、values-mcc440フォルダも削除

```
post-fs-data.sh
service.sh
/system/product/media/audio/ui/camera_click.ogg
```
を削除

・USB ケーブル接続時に画面がオンにならないよう変更
/system/product/overlay/treble-overlay-google-pixel6.apk をデコンパイルし
values/bools.xmlの
`<bool name="config_unplugTurnsOnScreen">false</bool>`
を削除

・電源メニューから緊急通報や機内モードを削除
/system/product/overlay/treble-overlay-google-pixel6.apk をデコンパイルし
values/arrays.xmlの
```
<string-array name="config_globalActionsList">
     <item>power</item>
     <item>restart</item>
</string-array>
```
を削除

です。

**Comment by KH0000001** [comment]
返信遅くなりすみません！
無事編集し、自分の思い通りにできました。
ありがとうございます✨![image](https://github.com/AndroPlus-org/magisk-module-pixel6/assets/98211309/4cce0602-952b-447c-a65e-1b6c8d3f8004)
